windup/windup-web-distribution

- pom.xml
- src/main/assembly/assembly-offline.xml
https://issues.jboss.org/browse/WINDUP-1174
> fixes https://issues.jboss.org/browse/WINDUP-1174, and absolute paths in assembly to not be platform dependent

- src/main/cli/setup-jms.cli
this was forgotten while creating the queue in windup-web
> added queue for discovery of packages

- pom.xml
- src/main/cli/adding-redirect.cli
- src/main/wildfly_overlay/windup-web-redirect/index.html
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/581
This add a static content into Wildfly and add new file handler for using it for / (root server URL)
> taiga task #581 Adding redirect from root URL

- src/main/wildfly_overlay/themes/rhamt/login/login.ftl
- src/main/wildfly_overlay/themes/rhamt/login/resources/css/login.css
Link only “documentation”
Second line should not be bold
> taiga task#790: Add one empty line between text

- src/main/resources/switch_to_automatic_authentication.bat
- src/main/resources/switch_to_automatic_authentication.sh
Taiga task #883.
Fix path to auto_login and login_required.theme.properties files.
> 883 - Fix path to switch auto login/auth required scripts

- src/main/wildfly_overlay/themes/rhamt/login/login.ftl
- src/main/wildfly_overlay/themes/rhamt/login/resources/css/login.css
Taiga task #937 - Login page.
Change positioning and eventually hide RHAMT logo for certain small resolutions.
> 937 - Improve responsiveness of login page

- src/main/wildfly_overlay/themes/rhamt/login/login.ftl
- src/main/wildfly_overlay/themes/rhamt/login/resources/css/login.css
Taiga task #937 - login page
- Text changes.
- Capitalize button labels.
> 937 - Update login page.

- src/main/cli/setup-eap.cli
Tested with development environment - WF 10.0.1.
Resolves WINDUP-1413
> T985 Resolve or remove warning messages from log - raise the log level.

- src/main/resources/openshift/app/configuration/eap.cli.original
The value has been aligned to https://github.com/windup/windup-web-distribution/blob/master/src/main/cli/setup-eap.cli#L8
> WINDUP-1393 OpenShift: Increase 'max-post-size' value

- src/main/cli/setup-eap.cli
- reorganize setup-eap.cli
- update logging configuration to filter analysis logs
> Add analysis logging filtering

- src/main/resources/openshift/deploy.sh
- src/main/resources/openshift/templates/rhamt-template.json
This also removes the last couple of steps. I can't tell that those effectively do anything as the application is built and started even without them.
> Added persistent volume claim for rhamt

- build_eap71.sh
- pom.xml
- src/main/cli/adding-redirect.cli
- src/main/resources/openshift/app/configuration/eap.cli
https://issues.jboss.org/browse/WINDUP-1994
> WINDUP-1994: Update windup-web-distribution to eap 7.1

- LICENSE
https://issues.jboss.org/browse/WINDUP-2370
> WINDUP-2370 Add LICENSE

- pom.xml
Upgraded to the recently released version of windup-keycloak-tool
> upgraded windup-keycloak-tool to 5.2.0.Final version

- pom.xml
https://issues.redhat.com/browse/WINDUP-2667
> WINDUP-2667: version upgrade

- src/main/resources/run_mta.sh
https://issues.redhat.com/browse/WINDUP-2620
> WINDUP-2620-reset-value-to-ulimit

- src/main/resources/run_mta.sh
https://issues.redhat.com/browse/WINDUP-2704
> WINDUP-2704 Changed requested limit

- src/main/resources/run_mta.sh
https://issues.redhat.com/browse/WINDUP-2704
Port of #67
> WINDUP-2704 Changed requested limit (#67)

- pom.xml
https://issues.redhat.com/browse/WINDUP-2789
> WINDUP-2789: change to pom version for new release

- pom.xml
- src/main/cli/setup-windup-keycloak-properties.cli
https://issues.redhat.com/browse/WINDUP-3181
> [WINDUP-3181] - MTA WebUI - Remove old WebUI Context

- README.asciidoc
- settings.xml
I'm adding the settings.xml file (and some documentation) so we can build with SNAPSHOTs
> Adding settings.xml file

- src/main/resources/run_mta.bat
- src/main/resources/run_mta.sh
https://issues.redhat.com/browse/WINDUP-3321
> [WINDUP-3321] - JDK11 upgrade - MTA Web Console Script

- .github/workflows/pull_request_push_build.yml
- settings.xml
> Added build for PRs and push events

- pom.xml
- src/main/assembly/assembly-offline.xml
- src/main/wildfly_overlay/modules/com/h2database/h2/main/module.xml
* WINDUP-3792 Made H2 version a build time property
* reuse version.h2
---------
> WINDUP-3792 Made H2 version a build time property (#103)

- pom.xml
- src/main/assembly/assembly-offline.xml
- src/main/wildfly_overlay/modules/com/h2database/h2/main/module.xml
> [releases/6.1.z] WINDUP-3792 Made H2 version a build time property

- mta-web-distribution/pom.xml
- mtr-web-distribution/pom.xml
- pom.xml
- tackle-web-distribution/pom.xml
- windup-web-distribution/pom.xml
This reverts commit 7dff286e5cf45b13c10954ecda85d2f079a56ec1.
> Revert "🏁 Releasing version 6.3.1.Final"

- src/main/cli/setup.cli
https://issues.redhat.com/browse/WINDUP-4072
> [WINDUP-4072] - Disable http2

- src/main/cli/setup.cli
> Disable http2

- pom.xml
- settings.xml
https://issues.sonatype.org/browse/OSSRH-96863
Depends on:
- https://github.com/windup/windup-openshift/pull/84
> Move to s01.oss.sonatype.org Sonatype repository

- pom.xml
- settings.xml
Backport https://github.com/windup/windup-web-distribution/pull/114
> [releases/6.3.z] Move to s01.oss.sonatype.org Sonatype repository (#114)
